models:
  - name: hotpot_qa_jcd_seed42
    type: RouterModule
    weight: 1.0

  - name: hotpot_qa_jcd_seed526
    type: RouterModule
    weight: 1.0

  - name: hotpot_qa_jcd_seed724
    type: RouterModule
    weight: 1.0
